formatter: markdown table

sections:
  hide:
    - header
    - footer

content: |-
  ## Example

  ### Basic

  ```terraform
  {{ include "examples/basic/main.tf" }}
  ```

  <!-- markdownlint-disable MD033 Allow inline html for generated markdown -->

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md

sort:
  enabled: true
  by: type

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
