name: release-main

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]') && ! contains(github.event.head_commit.message, 'docs:')"
    steps:
      - name: release-module
        uses: mjheitland/github-actions/terraform-module-release@v1
