name: validate-and-test-on-pr

on:
  workflow_dispatch:

  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
  security-events: write

# true = cancel any running job and start a new job with the current source code
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: terraform-validate
        uses: mjheitland/github-actions/terraform-validate@v1

      - name: assume-role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          aws-region: ${{ secrets.REGION }}

      - name: terraform-test
        uses: mjheitland/github-actions/terraform-test@v1
